# Generated by Django 5.1.5 on 2025-01-29 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLMatch',
            fields=[
                ('match_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=20)),
                ('week', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'db_table': 'nfl_match',
            },
        ),
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('player_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'db_table': 'nfl_player',
            },
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('team_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'nfl_team',
            },
        ),
        migrations.CreateModel(
            name='NFLPlayerStat',
            fields=[
                ('stat_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=10)),
                ('C', models.IntegerField()),
                ('ATT', models.IntegerField()),
                ('YDS', models.IntegerField()),
                ('AVG', models.FloatField()),
                ('TD', models.IntegerField()),
                ('interception', models.IntegerField()),
                ('SACK', models.IntegerField()),
                ('trying_SACK', models.IntegerField()),
                ('QBR', models.FloatField()),
                ('RTG', models.FloatField()),
                ('CAR', models.IntegerField()),
                ('LONG', models.IntegerField()),
                ('REC', models.IntegerField()),
                ('TGTS', models.IntegerField()),
                ('FUM', models.IntegerField()),
                ('LOST', models.IntegerField()),
                ('TOT', models.IntegerField()),
                ('SOLO', models.IntegerField()),
                ('SACKS', models.IntegerField()),
                ('TFL', models.IntegerField()),
                ('PD', models.IntegerField()),
                ('QB_HTS', models.IntegerField()),
                ('NO', models.IntegerField()),
                ('FG', models.IntegerField()),
                ('trying_FG', models.IntegerField()),
                ('PCT', models.IntegerField()),
                ('XP', models.IntegerField()),
                ('trying_XP', models.IntegerField()),
                ('PTS', models.IntegerField()),
                ('TB', models.IntegerField()),
                ('In_20', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflteam')),
            ],
            options={
                'verbose_name': 'Статистика грока',
                'verbose_name_plural': 'Статистика игроков',
                'db_table': 'nfl_player_stat',
            },
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='nfl.nflteam'),
        ),
        migrations.AddField(
            model_name='nflmatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='nfl.nflteam'),
        ),
        migrations.CreateModel(
            name='NFLBet',
            fields=[
                ('bet_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ML_team1_parlay', models.FloatField(blank=True, null=True)),
                ('ML_team2_parlay', models.FloatField(blank=True, null=True)),
                ('ML_result', models.CharField(blank=True, max_length=36, null=True)),
                ('total', models.FloatField()),
                ('over_total_parlay', models.FloatField(blank=True, null=True)),
                ('under_total_parlay', models.FloatField(blank=True, null=True)),
                ('total_result', models.CharField(blank=True, max_length=10, null=True)),
                ('spread_team1', models.FloatField(blank=True, null=True)),
                ('spread_team1_parlay', models.FloatField(blank=True, null=True)),
                ('spread_team2', models.FloatField(blank=True, null=True)),
                ('spread_team2_parlay', models.FloatField(blank=True, null=True)),
                ('spread_result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflmatch')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_as_team1', to='nfl.nflteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets_as_team2', to='nfl.nflteam')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'db_table': 'nfl_bet',
            },
        ),
        migrations.CreateModel(
            name='NFLTeamPtsStat',
            fields=[
                ('team_pts_stat_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('totalMissed', models.IntegerField()),
                ('total_Q1', models.IntegerField()),
                ('total_Q1Missed', models.IntegerField()),
                ('total_Q2', models.IntegerField()),
                ('total_Q2Missed', models.IntegerField()),
                ('total_Q3', models.IntegerField()),
                ('total_Q3Missed', models.IntegerField()),
                ('total_Q4', models.IntegerField()),
                ('total_Q4Missed', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflteam')),
            ],
            options={
                'verbose_name': 'Статистика команды по очкам',
                'verbose_name_plural': 'Статистика команд по очкам',
                'db_table': 'nfl_team_pts_stat',
            },
        ),
        migrations.CreateModel(
            name='NFLTeamStat',
            fields=[
                ('team_stat_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.nflteam')),
            ],
            options={
                'verbose_name': 'Статистика команды',
                'verbose_name_plural': 'Статистика команд',
                'db_table': 'nfl_team_stat',
            },
        ),
    ]
