# Generated by Django 5.1.5 on 2025-01-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflbet',
            old_name='bet_ID',
            new_name='bet_id',
        ),
        migrations.RenameField(
            model_name='nflmatch',
            old_name='match_ID',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='nflplayer',
            old_name='player_ID',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='nflplayerstat',
            old_name='stat_ID',
            new_name='stat_id',
        ),
        migrations.RenameField(
            model_name='nflteam',
            old_name='team_ID',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='nflteamptsstat',
            old_name='team_pts_stat_ID',
            new_name='team_pts_stat_id',
        ),
        migrations.RenameField(
            model_name='nflteamstat',
            old_name='team_stat_ID',
            new_name='team_stat_id',
        ),
    ]
