# Generated by Django 5.1.5 on 2025-01-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_rename_ml_result_nflbet_ml_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflplayerstat',
            old_name='trying_FG',
            new_name='trying_fg',
        ),
        migrations.RenameField(
            model_name='nflplayerstat',
            old_name='trying_SACK',
            new_name='trying_sack',
        ),
        migrations.RenameField(
            model_name='nflteamptsstat',
            old_name='totalMissed',
            new_name='total_missed',
        ),
    ]
