# Generated by Django 5.1.5 on 2025-01-29 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_rename_trying_fg_nflplayerstat_trying_fg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayer',
            name='player_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nflplayerstat',
            name='stat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
