# Generated by Django 5.1.5 on 2025-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_alter_nflplayerstat_att_alter_nflplayerstat_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayerstat',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
