# Generated by Django 5.1.5 on 2025-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0008_alter_nflplayerstat_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обновление NFL',
                'verbose_name_plural': 'Обновления NFL',
                'db_table': 'nfl_update',
            },
        ),
    ]
