# Generated by Django 5.1.5 on 2025-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0009_nflupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflmatch',
            name='stage',
            field=models.CharField(max_length=50),
        ),
    ]
