# Generated by Django 5.1.5 on 2025-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(choices=[('NBA', 'NBA'), ('NHL', 'NHL'), ('NFL', 'NFL')], max_length=100, unique=True),
        ),
    ]
