# Generated by Django 5.1.5 on 2025-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_rename_bet_id_nbabet_bet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='match_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='player_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
