# Generated by Django 5.1.5 on 2025-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_alter_nbamatch_match_id_alter_nbaplayer_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='match_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='player_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
