# Generated by Django 5.1.5 on 2025-01-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_rename_ml_result_nbabet_ml_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbateamptsstat',
            old_name='total_q1Missed',
            new_name='total_q1_missed',
        ),
        migrations.RenameField(
            model_name='nbateamptsstat',
            old_name='total_q2Missed',
            new_name='total_q2_missed',
        ),
        migrations.RenameField(
            model_name='nbateamptsstat',
            old_name='total_q3Missed',
            new_name='total_q3_missed',
        ),
        migrations.RenameField(
            model_name='nbateamptsstat',
            old_name='total_q4Missed',
            new_name='total_q4_missed',
        ),
    ]
