# Generated by Django 5.1.5 on 2025-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_alter_nbaplayerstat_ast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обновление NBA',
                'verbose_name_plural': 'Обновления NBA',
                'db_table': 'nba_update',
            },
        ),
    ]
