# Generated by Django 5.1.5 on 2025-02-13 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_nbaupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='match_id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nbamatch',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NBAMoneylineBet',
            fields=[
                ('moneyline_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('team1_odds', models.FloatField(blank=True, null=True)),
                ('team2_odds', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.nbamatch')),
            ],
            options={
                'verbose_name': 'Ставка на победу',
                'verbose_name_plural': 'Ставки на победу',
                'db_table': 'nba_moneyline_bet',
            },
        ),
        migrations.CreateModel(
            name='NBASpreadBet',
            fields=[
                ('spread_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('spread_team1', models.FloatField(blank=True, null=True)),
                ('spread_team1_odds', models.FloatField(blank=True, null=True)),
                ('spread_team2', models.FloatField(blank=True, null=True)),
                ('spread_team2_odds', models.FloatField(blank=True, null=True)),
                ('spread_result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.nbamatch')),
            ],
            options={
                'verbose_name': 'Ставка на фору',
                'verbose_name_plural': 'Ставки на форы',
                'db_table': 'nba_spread_bet',
            },
        ),
        migrations.CreateModel(
            name='NBATotalBet',
            fields=[
                ('total_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('total', models.FloatField()),
                ('over_odds', models.FloatField(blank=True, null=True)),
                ('under_odds', models.FloatField(blank=True, null=True)),
                ('total_result', models.CharField(blank=True, max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nba.nbamatch')),
            ],
            options={
                'verbose_name': 'Ставка на тотал',
                'verbose_name_plural': 'Ставки на тоталы',
                'db_table': 'nba_total_bet',
            },
        ),
        migrations.DeleteModel(
            name='NBABet',
        ),
    ]
