# Generated by Django 5.1.5 on 2025-02-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_alter_nbamatch_match_id_alter_nbamatch_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='nba.nbateam'),
        ),
        migrations.AlterField(
            model_name='nbamatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='nba.nbateam'),
        ),
    ]
