# Generated by Django 5.1.5 on 2025-02-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0010_alter_nbamatch_team1_alter_nbamatch_team2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbahandicapbet',
            old_name='handicap_team1',
            new_name='handicap',
        ),
        migrations.RemoveField(
            model_name='nbahandicapbet',
            name='handicap_team2',
        ),
    ]
