# Generated by Django 5.1.5 on 2025-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_rename_handicap_team1_nbahandicapbet_handicap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayerstat',
            name='position',
            field=models.CharField(choices=[('starter', 'Стартер'), ('bench', 'Скамейка')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nbateamstat',
            name='result',
            field=models.CharField(choices=[('win', 'Победа'), ('lose', 'Проигрышь'), ('draw', 'Ничья')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nbateamstat',
            name='status',
            field=models.CharField(choices=[('home', 'Дом'), ('away', 'Выезд')], max_length=10),
        ),
    ]
