# Generated by Django 5.1.5 on 2025-02-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0012_alter_nbaplayerstat_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
