# Generated by Django 5.1.5 on 2025-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0014_alter_nbamoneylinebet_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbatotalbet',
            name='period',
            field=models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('2nd_half', '2-я Половина'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20),
        ),
    ]
