# Generated by Django 5.1.5 on 2025-03-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0018_remove_nbahandicapbet_handicap_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='second_name',
        ),
    ]
