# Generated by Django 5.1.5 on 2025-03-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0019_remove_nbateam_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateamstat',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='attempted_three_pt',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='dreb',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='fg',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='ft',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='oreb',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='reb',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='stl',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='three_pt',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='trying_fg',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='trying_ft',
        ),
        migrations.RemoveField(
            model_name='nbateamstat',
            name='turnovers',
        ),
    ]
