# Generated by Django 5.1.5 on 2025-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0020_remove_nbateamstat_ast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('preseason', 'Пресезон')], max_length=50, null=True),
        ),
    ]
