# Generated by Django 5.1.5 on 2025-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0021_alter_nbamatch_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbamatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('preseason', 'Пресезон'), ('in-season championship', 'Внутрисезонный финал'), ('in-season semifinals', 'Внутрисезонный полуфинал'), ('in-season quarterfinals', 'Внутрисезонный 1/4')], max_length=50, null=True),
        ),
    ]
