# Generated by Django 5.1.5 on 2025-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0023_alter_nbatotalbet_total_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbamatch',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nbamatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('preseason', 'Пресезон'), ('in-season championship', 'Внутрисезонный финал'), ('in-season semifinals', 'Внутрисезонный полуфинал'), ('in-season quarterfinals', 'Внутрисезонный четвертьфинал'), ('east finals', 'Финал востока'), ('west finals', 'Финал запада'), ('east semifinals', 'Полуфинал востока'), ('west semifinals', 'Полуфинал запада'), ('east 1st round', 'Первый раунд востока'), ('west 1st round', 'Первый раунд запада'), ('play-in east 9th place vs 10th place', 'Play-in востока'), ('play-in west 9th place vs 10th place', 'Play-in запада'), ('play-in east 7th place vs 8th place', 'Play-in востока'), ('play-in west 7th place vs 8th place', 'Play-in запада'), ('play-in east 8th seed', 'Play-in востока'), ('play-in west 8th seed', 'Play-in запада'), ('cup group play', 'Кубок - групповая стадия'), ('cup quarterfinals', 'Кубок - четвертьфинал'), ('cup championship', 'Кубок - чемпионат')], max_length=50, null=True),
        ),
    ]
