# Generated by Django 5.1.5 on 2025-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0026_nbateam_logo_alter_nbamatch_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='conference',
            field=models.CharField(blank=True, choices=[('Eastern Conference', 'Восточная Конференция'), ('Western Conference', 'Западная Конференция')], max_length=100, null=True),
        ),
    ]
