# Generated by Django 5.1.5 on 2025-02-21 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLBMatch',
            fields=[
                ('match_id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'db_table': 'mlb_match',
            },
        ),
        migrations.CreateModel(
            name='MLBTeam',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'mlb_team',
            },
        ),
        migrations.CreateModel(
            name='MLBUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Обновление MLB',
                'verbose_name_plural': 'Обновления MLB',
                'db_table': 'mlb_update',
            },
        ),
        migrations.CreateModel(
            name='MLBHandicapBet',
            fields=[
                ('handicap_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('handicap_team1_odds', models.FloatField(blank=True, null=True)),
                ('handicap_team2_odds', models.FloatField(blank=True, null=True)),
                ('handicap_result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
            ],
            options={
                'verbose_name': 'Ставка на фору',
                'verbose_name_plural': 'Ставки на форы',
                'db_table': 'mlb_handicap_bet',
            },
        ),
        migrations.CreateModel(
            name='MLBMoneylineBet',
            fields=[
                ('moneyline_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('team1_odds', models.FloatField(blank=True, null=True)),
                ('team2_odds', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
            ],
            options={
                'verbose_name': 'Ставка на победу',
                'verbose_name_plural': 'Ставки на победу',
                'db_table': 'mlb_moneyline_bet',
            },
        ),
        migrations.AddField(
            model_name='mlbmatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='mlb.mlbteam'),
        ),
        migrations.AddField(
            model_name='mlbmatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='mlb.mlbteam'),
        ),
        migrations.CreateModel(
            name='MLBTotalBet',
            fields=[
                ('total_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_half', '1-я Половина'), ('2nd_half', '2-я Половина'), ('1st_quarter', '1-я Четверть'), ('2nd_quarter', '2-я Четверть'), ('3rd_quarter', '3-я Четверть'), ('4th_quarter', '4-я Четверть')], max_length=20)),
                ('total', models.FloatField()),
                ('over_odds', models.FloatField(blank=True, null=True)),
                ('under_odds', models.FloatField(blank=True, null=True)),
                ('total_result', models.CharField(blank=True, max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
            ],
            options={
                'verbose_name': 'Ставка на тотал',
                'verbose_name_plural': 'Ставки на тоталы',
                'db_table': 'mlb_total_bet',
            },
        ),
    ]
