# Generated by Django 5.1.5 on 2025-02-21 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBPlayer',
            fields=[
                ('player_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'db_table': 'mlb_player',
            },
        ),
        migrations.CreateModel(
            name='MLBPlayerStat',
            fields=[
                ('stat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('hitter', 'Бьющий'), ('pitcher ', 'Подающий')], max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('ab', models.IntegerField(null=True)),
                ('r', models.IntegerField(null=True)),
                ('h', models.IntegerField(null=True)),
                ('rbi', models.IntegerField(null=True)),
                ('hr', models.IntegerField(null=True)),
                ('bb', models.IntegerField(null=True)),
                ('k', models.IntegerField(null=True)),
                ('avg', models.IntegerField(null=True)),
                ('obp', models.IntegerField(null=True)),
                ('slg', models.IntegerField(null=True)),
                ('ip', models.IntegerField(null=True)),
                ('er', models.IntegerField(null=True)),
                ('pc', models.IntegerField(null=True)),
                ('st', models.IntegerField(null=True)),
                ('era', models.IntegerField(null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbteam')),
            ],
            options={
                'verbose_name': 'Статистика грока',
                'verbose_name_plural': 'Статистика игроков',
                'db_table': 'mlb_player_stat',
            },
        ),
        migrations.CreateModel(
            name='MLBTeamPtsStat',
            fields=[
                ('team_pts_stat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run', models.IntegerField()),
                ('run_missed', models.IntegerField()),
                ('hit', models.IntegerField()),
                ('hit_missed', models.IntegerField()),
                ('error', models.IntegerField()),
                ('error_missed', models.IntegerField()),
                ('run_i1', models.IntegerField()),
                ('run_i1_missed', models.IntegerField()),
                ('run_i2', models.IntegerField()),
                ('run_i2_missed', models.IntegerField()),
                ('run_i3', models.IntegerField()),
                ('run_i3_missed', models.IntegerField()),
                ('run_i4', models.IntegerField()),
                ('run_i4_missed', models.IntegerField()),
                ('run_i5', models.IntegerField()),
                ('run_i5_missed', models.IntegerField()),
                ('run_i6', models.IntegerField()),
                ('run_i6_missed', models.IntegerField()),
                ('run_i7', models.IntegerField()),
                ('run_i7_missed', models.IntegerField()),
                ('run_i8', models.IntegerField()),
                ('run_i8_missed', models.IntegerField()),
                ('run_i9', models.IntegerField()),
                ('run_i9_missed', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbteam')),
            ],
            options={
                'verbose_name': 'Статистика команды по очкам',
                'verbose_name_plural': 'Статистика команд по очкам',
                'db_table': 'mlb_team_pts_stat',
            },
        ),
        migrations.CreateModel(
            name='MLBTeamStat',
            fields=[
                ('team_stat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('win', 'Победа'), ('lose', 'Проигрышь'), ('draw', 'Ничья')], max_length=10)),
                ('status', models.CharField(choices=[('home', 'Дом'), ('away', 'Выезд')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlb.mlbteam')),
            ],
            options={
                'verbose_name': 'Статистика команды',
                'verbose_name_plural': 'Статистика команд',
                'db_table': 'mlb_team_stat',
            },
        ),
    ]
