# Generated by Django 5.1.5 on 2025-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0002_mlbplayer_mlbplayerstat_mlbteamptsstat_mlbteamstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbteamptsstat',
            name='error_missed',
        ),
    ]
