# Generated by Django 5.1.5 on 2025-03-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0004_remove_mlbhandicapbet_handicap_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbteam',
            name='second_name',
        ),
    ]
