# Generated by Django 5.1.5 on 2025-03-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0005_remove_mlbteam_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i1',
            new_name='total_i1',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i1_missed',
            new_name='total_i1_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i2',
            new_name='total_i2',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i2_missed',
            new_name='total_i2_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i3',
            new_name='total_i3',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i3_missed',
            new_name='total_i3_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i4',
            new_name='total_i4',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i4_missed',
            new_name='total_i4_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i5',
            new_name='total_i5',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i5_missed',
            new_name='total_i5_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i6',
            new_name='total_i6',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i6_missed',
            new_name='total_i6_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i7',
            new_name='total_i7',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i7_missed',
            new_name='total_i7_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i8',
            new_name='total_i8',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i8_missed',
            new_name='total_i8_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i9',
            new_name='total_i9',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_i9_missed',
            new_name='total_i9_missed',
        ),
        migrations.RenameField(
            model_name='mlbteamptsstat',
            old_name='run_missed',
            new_name='total_missed',
        ),
    ]
