# Generated by Django 5.1.5 on 2025-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0006_rename_run_mlbteamptsstat_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlbplayerstat',
            name='avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mlbplayerstat',
            name='ip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mlbplayerstat',
            name='obp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mlbplayerstat',
            name='slg',
            field=models.FloatField(null=True),
        ),
    ]
