# Generated by Django 5.1.5 on 2025-04-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0008_alter_mlbplayerstat_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbmatch',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlbhandicapbet',
            name='handicap_team1_result',
            field=models.CharField(blank=True, choices=[('win', 'Победа'), ('draw', 'Ничья'), ('lose', 'Поражение')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mlbhandicapbet',
            name='handicap_team2_result',
            field=models.CharField(blank=True, choices=[('win', 'Победа'), ('draw', 'Ничья'), ('lose', 'Поражение')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mlbmatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('all-star', 'Матч всех звезд'), ('alwc', 'ALWC'), ('nlwc', 'NLWC'), ('nlds', 'NLDS'), ('alds', 'ALDS'), ('nlcs', 'NLCS'), ('alcs', 'ALCS'), ('world series', 'Мировая Серия')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mlbtotalbet',
            name='total_result',
            field=models.CharField(blank=True, choices=[('over', 'Больше'), ('draw', 'Равно'), ('under', 'Меньше')], max_length=10, null=True),
        ),
    ]
