# Generated by Django 5.1.5 on 2025-04-04 14:48

import mlb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0009_mlbmatch_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=mlb.models.team_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='mlbmatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('all-star', 'Матч всех звезд'), ('alwc', 'AL Wild Card'), ('nlwc', 'NL Wild Card'), ('nlds', 'NL Дивизионная Серия'), ('alds', 'AL Дивизионная Серия'), ('nlcs', 'NL Чемпионская Cерия'), ('alcs', 'AL Чемпионская Cерия'), ('world series', 'Мировая Серия'), ('world tour', 'Мировой Тур')], max_length=100, null=True),
        ),
    ]
