# Generated by Django 5.1.5 on 2025-04-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0010_mlbteam_logo_alter_mlbmatch_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlbteam',
            name='logo',
        ),
    ]
