# Generated by Django 5.1.5 on 2025-04-04 14:56

import mlb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0011_remove_mlbteam_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=mlb.models.team_logo_upload_path),
        ),
    ]
