# Generated by Django 5.1.5 on 2025-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_mlbteam_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbteam',
            name='league',
            field=models.CharField(blank=True, choices=[('American League', 'Американская Лига'), ('National League', 'Национальная Лига')], max_length=100, null=True),
        ),
    ]
