# Generated by Django 5.1.5 on 2025-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0004_rename_ml_result_nhlbet_ml_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='bs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='essv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='ga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='gv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='ht',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='pim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='plus_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='pn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='ppsv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='s',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='sa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='sm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='sv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='sv_procent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='tk',
            field=models.IntegerField(null=True),
        ),
    ]
