# Generated by Django 5.1.5 on 2025-01-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0005_alter_nhlplayerstat_a_alter_nhlplayerstat_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlmatch',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
