# Generated by Django 5.1.5 on 2025-02-20 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0007_nhlupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHLHandicapBet',
            fields=[
                ('handicap_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_period', '1-й Период'), ('2nd_period', '2-й Период'), ('3rd_period', '3-й Период')], max_length=20)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('handicap_team1_odds', models.FloatField(blank=True, null=True)),
                ('handicap_team2_odds', models.FloatField(blank=True, null=True)),
                ('handicap_result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlmatch')),
            ],
            options={
                'verbose_name': 'Ставка на фору',
                'verbose_name_plural': 'Ставки на форы',
                'db_table': 'nhl_handicap_bet',
            },
        ),
        migrations.CreateModel(
            name='NHLMoneylineBet',
            fields=[
                ('moneyline_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_period', '1-й Период'), ('2nd_period', '2-й Период'), ('3rd_period', '3-й Период')], max_length=20)),
                ('team1_odds', models.FloatField(blank=True, null=True)),
                ('team2_odds', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlmatch')),
            ],
            options={
                'verbose_name': 'Ставка на победу',
                'verbose_name_plural': 'Ставки на победу',
                'db_table': 'nhl_moneyline_bet',
            },
        ),
        migrations.CreateModel(
            name='NHLTotalBet',
            fields=[
                ('total_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_period', '1-й Период'), ('2nd_period', '2-й Период'), ('3rd_period', '3-й Период')], max_length=20)),
                ('total', models.FloatField()),
                ('over_odds', models.FloatField(blank=True, null=True)),
                ('under_odds', models.FloatField(blank=True, null=True)),
                ('total_result', models.CharField(blank=True, max_length=10, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlmatch')),
            ],
            options={
                'verbose_name': 'Ставка на тотал',
                'verbose_name_plural': 'Ставки на тоталы',
                'db_table': 'nhl_total_bet',
            },
        ),
        migrations.CreateModel(
            name='NHLXBet',
            fields=[
                ('x_bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('full_time', 'Весь Матч'), ('1st_period', '1-й Период'), ('2nd_period', '2-й Период'), ('3rd_period', '3-й Период')], max_length=20)),
                ('team1_odds', models.FloatField(blank=True, null=True)),
                ('draw', models.FloatField(blank=True, null=True)),
                ('team2_odds', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=36, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlmatch')),
            ],
            options={
                'verbose_name': 'Ставка на победу или ничью',
                'verbose_name_plural': 'Ставки на победу или ничью',
                'db_table': 'nhl_x_bet',
            },
        ),
        migrations.DeleteModel(
            name='NHLBet',
        ),
    ]
