# Generated by Django 5.1.5 on 2025-02-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0008_nhlhandicapbet_nhlmoneylinebet_nhltotalbet_nhlxbet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlmatch',
            name='match_id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
