# Generated by Django 5.1.5 on 2025-02-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0009_alter_nhlmatch_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlmatch',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
