# Generated by Django 5.1.5 on 2025-02-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0010_alter_nhlmatch_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlplayerstat',
            name='team',
            field=models.ForeignKey(choices=[('forward', 'Нападающий'), ('defenseman', 'Защитник'), ('goalie', 'Вратарь')], on_delete=django.db.models.deletion.CASCADE, to='nhl.nhlteam'),
        ),
    ]
