# Generated by Django 5.1.5 on 2025-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0012_remove_nhlhandicapbet_handicap_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t1',
            new_name='total_p1',
        ),
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t1_missed',
            new_name='total_p1_missed',
        ),
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t2',
            new_name='total_p2',
        ),
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t2_missed',
            new_name='total_p2_missed',
        ),
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t3',
            new_name='total_p3',
        ),
        migrations.RenameField(
            model_name='nhlteamptsstat',
            old_name='total_t3_missed',
            new_name='total_p3_missed',
        ),
    ]
