# Generated by Django 5.1.5 on 2025-04-04 14:48

import nhl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0013_rename_total_t1_nhlteamptsstat_total_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlmatch',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhlteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=nhl.models.team_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='nhlhandicapbet',
            name='handicap_team1_result',
            field=models.CharField(blank=True, choices=[('win', 'Победа'), ('draw', 'Ничья'), ('lose', 'Поражение')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nhlhandicapbet',
            name='handicap_team2_result',
            field=models.CharField(blank=True, choices=[('win', 'Победа'), ('draw', 'Ничья'), ('lose', 'Поражение')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nhlmatch',
            name='stage',
            field=models.CharField(blank=True, choices=[('regular', 'Регулярный сезон'), ('preseason', 'Пресезон'), ('in-season championship', 'Внутрисезонный финал'), ('in-season semifinals', 'Внутрисезонный полуфинал'), ('in-season quarterfinals', 'Внутрисезонный четвертьфинал'), ('east finals', 'Финал востока'), ('west finals', 'Финал запада'), ('east semifinals', 'Полуфинал востока'), ('west semifinals', 'Полуфинал запада'), ('east 1st round', 'Первый раунд востока'), ('west 1st round', 'Первый раунд запада'), ('stanley cup final', 'Финал Кубка Стенли')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nhltotalbet',
            name='total_result',
            field=models.CharField(blank=True, choices=[('over', 'Больше'), ('draw', 'Равно'), ('under', 'Меньше')], max_length=10, null=True),
        ),
    ]
