# Generated by Django 5.1.5 on 2025-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0014_nhlmatch_time_nhlteam_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlteam',
            name='conference',
            field=models.CharField(blank=True, choices=[('Eastern Conference', 'Восточная Конференция'), ('Western Conference', 'Западная Конференция')], max_length=100, null=True),
        ),
    ]
